openapi: 3.0.0
info:
  title: Olympics Management System API
  description: "Clean CRUD API with Users, Athletes, Competitions, Results"
  version: 3.0.0
servers:
- url: https://virtserver.swaggerhub.com/stu2401321073organiz/Olympics_Management_System/3.0.0
  description: SwaggerHub API Auto Mocking
- url: https://localhost:5246/api
paths:
  /auth/register:
    post:
      summary: Register user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateDTO"
        required: true
      responses:
        "200":
          description: Success
  /auth/login:
    post:
      summary: Login user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginDTO"
        required: true
      responses:
        "200":
          description: JWT token
  /auth/logout:
    post:
      summary: Logout user
      responses:
        "200":
          description: Logged out
  /users:
    get:
      summary: Get all users
      responses:
        "200":
          description: List users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserReadDTO"
    post:
      summary: Create user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateDTO"
        required: true
      responses:
        "200":
          description: Created
  /users/{id}:
    get:
      summary: Get user by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: User
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserReadDTO"
    put:
      summary: Update user
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdateDTO"
        required: true
      responses:
        "204":
          description: Updated
    delete:
      summary: Delete user
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "204":
          description: Deleted
  /athletes:
    get:
      summary: Get all athletes
      responses:
        "200":
          description: List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AthleteReadDTO"
    post:
      summary: Create athlete
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AthleteCreateDTO"
        required: true
      responses:
        "200":
          description: Created
  /athletes/{id}:
    get:
      summary: Get athlete by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: Athlete
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AthleteReadDTO"
    put:
      summary: Update athlete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AthleteUpdateDTO"
        required: true
      responses:
        "204":
          description: Updated
    delete:
      summary: Delete athlete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "204":
          description: Deleted
  /competitions:
    get:
      summary: Get all competitions
      responses:
        "200":
          description: List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CompetitionReadDTO"
    post:
      summary: Create competition
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CompetitionCreateDTO"
        required: true
      responses:
        "200":
          description: Created
  /competitions/{id}:
    get:
      summary: Get competition by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: Competition
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompetitionReadDTO"
    put:
      summary: Update competition
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CompetitionUpdateDTO"
        required: true
      responses:
        "204":
          description: Updated
    delete:
      summary: Delete competition
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "204":
          description: Deleted
  /results:
    get:
      summary: Get all results
      responses:
        "200":
          description: List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ResultReadDTO"
    post:
      summary: Create result
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResultCreateDTO"
        required: true
      responses:
        "200":
          description: Created
  /results/{id}:
    get:
      summary: Get result by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: Result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResultReadDTO"
    put:
      summary: Update result
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResultUpdateDTO"
        required: true
      responses:
        "204":
          description: Updated
    delete:
      summary: Delete result
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "204":
          description: Deleted
components:
  schemas:
    UserCreateDTO:
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    UserUpdateDTO:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    UserLoginDTO:
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    UserReadDTO:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
    AthleteCreateDTO:
      required:
      - country
      - firstName
      - lastName
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        country:
          type: string
        gender:
          type: integer
        birthDate:
          type: string
          format: date
        height:
          type: integer
        weight:
          type: number
        isActive:
          type: boolean
        imageUrl:
          type: string
    AthleteUpdateDTO:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        country:
          type: string
        gender:
          type: integer
        birthDate:
          type: string
          format: date
        height:
          type: integer
        weight:
          type: number
        isActive:
          type: boolean
        imageUrl:
          type: string
    AthleteReadDTO:
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        country:
          type: string
        gender:
          type: integer
        birthDate:
          type: string
          format: date
        height:
          type: integer
        weight:
          type: number
        isActive:
          type: boolean
        imageUrl:
          type: string
    CompetitionCreateDTO:
      required:
      - eventDate
      - eventName
      - gameType
      - sport
      - venue
      type: object
      properties:
        eventName:
          type: string
        sport:
          type: string
        gameType:
          type: integer
        eventDate:
          type: string
          format: date-time
        venue:
          type: string
        prizePool:
          type: number
        imageUrl:
          type: string
    CompetitionUpdateDTO:
      type: object
      properties:
        eventName:
          type: string
        sport:
          type: string
        gameType:
          type: integer
        eventDate:
          type: string
          format: date-time
        venue:
          type: string
        prizePool:
          type: number
        imageUrl:
          type: string
    CompetitionReadDTO:
      type: object
      properties:
        id:
          type: integer
        eventName:
          type: string
        sport:
          type: string
        gameType:
          type: integer
        eventDate:
          type: string
          format: date-time
        venue:
          type: string
        prizePool:
          type: number
        imageUrl:
          type: string
    ResultCreateDTO:
      required:
      - athleteId
      - competitionId
      - medal
      - score
      type: object
      properties:
        athleteId:
          type: integer
        competitionId:
          type: integer
        score:
          type: number
        rank:
          type: integer
        medal:
          type: integer
        achievedOn:
          type: string
          format: date-time
        isRecord:
          type: boolean
        imageUrl:
          type: string
    ResultUpdateDTO:
      type: object
      properties:
        athleteId:
          type: integer
        competitionId:
          type: integer
        score:
          type: number
        rank:
          type: integer
        medal:
          type: integer
        achievedOn:
          type: string
          format: date-time
        isRecord:
          type: boolean
        imageUrl:
          type: string
    ResultReadDTO:
      type: object
      properties:
        id:
          type: integer
        athleteId:
          type: integer
        competitionId:
          type: integer
        score:
          type: number
        rank:
          type: integer
        medal:
          type: integer
        achievedOn:
          type: string
          format: date-time
        isRecord:
          type: boolean
        imageUrl:
          type: string
